# Generated by Django 4.0.4 on 2022-05-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nazwa'),
        ),
        migrations.CreateModel(
            name='InstitutionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nazwa')),
                ('description', models.TextField(verbose_name='Opis')),
                ('type', models.CharField(choices=[('F', 'Fundacja'), ('OP', 'Organizacja Pozarządowa'), ('ZL', 'Zbiórka Lokalna')], default='F', max_length=23, verbose_name='Typ')),
                ('categories', models.ManyToManyField(related_name='institution_category', to='donation_app.categorymodel')),
            ],
        ),
    ]
