# Generated by Django 4.0.4 on 2022-05-19 12:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation_app', '0002_alter_categorymodel_name_institutionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionmodel',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Opis'),
        ),
        migrations.CreateModel(
            name='DonationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='ilość')),
                ('address', models.CharField(max_length=200, verbose_name='Adres')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='(?<!\\w)(\\(?(\\+|00)?48\\)?)?[ -]?\\d{3}[ -]?\\d{3}[ -]?\\d{3}(?!\\w)')], verbose_name='Numer telefonu')),
                ('city', models.CharField(max_length=50, verbose_name='Miasto')),
                ('zip_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='\\d{2}-\\d{3}')], verbose_name='Kod pocztowy')),
                ('pick_up_date', models.DateField(verbose_name='Data')),
                ('pick_up_time', models.TimeField(verbose_name='Godzina')),
                ('pick_up_comment', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(300)], verbose_name='Opis')),
                ('categories', models.ManyToManyField(related_name='donation_category', to='donation_app.categorymodel')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution', to='donation_app.institutionmodel')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='donator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
