# Generated by Django 4.0.4 on 2022-05-19 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation_app', '0003_alter_institutionmodel_description_donationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donator', to=settings.AUTH_USER_MODEL),
        ),
    ]
