# Generated by Django 4.0.4 on 2022-05-19 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0004_alter_donationmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='pick_up_comment',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(300)], verbose_name='Opis'),
        ),
    ]
