# Generated by Django 4.0.4 on 2022-05-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0006_alter_institutionmodel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationmodel',
            old_name='user',
            new_name='user_donator',
        ),
    ]
