# Generated by Django 4.0.4 on 2022-06-03 09:37
import os

from django.contrib.auth import get_user_model
from django.db import migrations


def create_super_user(apps, schema_editor):
    Account = get_user_model()

    DJANGO_SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL')
    DJANGO_SU_FIRST_NAME = os.environ.get('DJANGO_SU_FIRST_NAME')
    DJANGO_SU_LAST_NAME = os.environ.get('DJANGO_SU_LAST_NAME')
    DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD')

    Account.objects.create_superuser(
        email=DJANGO_SU_EMAIL,
        first_name=DJANGO_SU_FIRST_NAME,
        last_name=DJANGO_SU_LAST_NAME,
        password=DJANGO_SU_PASSWORD,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_super_user)
    ]
