# Generated by Django 4.0.4 on 2022-06-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
